/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91Char93RouteImport } from './routes/[-]'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as SupportRouteImport } from './routes/support'
import { Route as Char91Char93IndexRouteImport } from './routes/[-]/index'
import { Route as Char91Char93AspectRouteImport } from './routes/[-]/$aspect'
import { Route as Char91Char93AccountRouteImport } from './routes/[-]/account'
import { Route as Char91Char93AgentsRouteImport } from './routes/[-]/agents'
import { Route as Char91Char93ExploreRouteImport } from './routes/[-]/explore'
import { Route as Char91Char93ProfileRouteImport } from './routes/[-]/profile'
import { Route as Char91Char93TasksRouteImport } from './routes/[-]/tasks'
import { Route as Char91Char93TeamRouteImport } from './routes/[-]/team'
import { Route as Char91Char93TodayRouteImport } from './routes/[-]/today'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as AuthenticationPasswordResetRouteImport } from './routes/authentication/password-reset'
import { Route as Char91Char93AccountIndexRouteImport } from './routes/[-]/account/index'
import { Route as Char91Char93AccountSecurityRouteImport } from './routes/[-]/account/security'
import { Route as Char91Char93InvitationInvitationIdRouteImport } from './routes/[-]/invitation.$invitationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93Route = Char91Char93RouteImport.update({
  id: '/-',
  path: '/-',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93IndexRoute = Char91Char93IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93AspectRoute = Char91Char93AspectRouteImport.update({
  id: '/$aspect',
  path: '/$aspect',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93AccountRoute = Char91Char93AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93AgentsRoute = Char91Char93AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93ExploreRoute = Char91Char93ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93ProfileRoute = Char91Char93ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93TasksRoute = Char91Char93TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93TeamRoute = Char91Char93TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => Char91Char93Route,
} as any)
const Char91Char93TodayRoute = Char91Char93TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => Char91Char93Route,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationPasswordResetRoute =
  AuthenticationPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => AuthenticationRoute,
  } as any)
const Char91Char93AccountIndexRoute =
  Char91Char93AccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char91Char93AccountRoute,
  } as any)
const Char91Char93AccountSecurityRoute =
  Char91Char93AccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => Char91Char93AccountRoute,
  } as any)
const Char91Char93InvitationInvitationIdRoute =
  Char91Char93InvitationInvitationIdRouteImport.update({
    id: '/invitation/$invitationId',
    path: '/invitation/$invitationId',
    getParentRoute: () => Char91Char93Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/-': typeof Char91Char93RouteWithChildren
  '/authentication': typeof AuthenticationRouteWithChildren
  '/support': typeof SupportRoute
  '/-/$aspect': typeof Char91Char93AspectRoute
  '/-/account': typeof Char91Char93AccountRouteWithChildren
  '/-/agents': typeof Char91Char93AgentsRoute
  '/-/explore': typeof Char91Char93ExploreRoute
  '/-/profile': typeof Char91Char93ProfileRoute
  '/-/tasks': typeof Char91Char93TasksRoute
  '/-/team': typeof Char91Char93TeamRoute
  '/-/today': typeof Char91Char93TodayRoute
  '/authentication/password-reset': typeof AuthenticationPasswordResetRoute
  '/-/': typeof Char91Char93IndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/-/account/security': typeof Char91Char93AccountSecurityRoute
  '/-/invitation/$invitationId': typeof Char91Char93InvitationInvitationIdRoute
  '/-/account/': typeof Char91Char93AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/support': typeof SupportRoute
  '/-/$aspect': typeof Char91Char93AspectRoute
  '/-/agents': typeof Char91Char93AgentsRoute
  '/-/explore': typeof Char91Char93ExploreRoute
  '/-/profile': typeof Char91Char93ProfileRoute
  '/-/tasks': typeof Char91Char93TasksRoute
  '/-/team': typeof Char91Char93TeamRoute
  '/-/today': typeof Char91Char93TodayRoute
  '/authentication/password-reset': typeof AuthenticationPasswordResetRoute
  '/-': typeof Char91Char93IndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/-/account/security': typeof Char91Char93AccountSecurityRoute
  '/-/invitation/$invitationId': typeof Char91Char93InvitationInvitationIdRoute
  '/-/account': typeof Char91Char93AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/-': typeof Char91Char93RouteWithChildren
  '/authentication': typeof AuthenticationRouteWithChildren
  '/support': typeof SupportRoute
  '/-/$aspect': typeof Char91Char93AspectRoute
  '/-/account': typeof Char91Char93AccountRouteWithChildren
  '/-/agents': typeof Char91Char93AgentsRoute
  '/-/explore': typeof Char91Char93ExploreRoute
  '/-/profile': typeof Char91Char93ProfileRoute
  '/-/tasks': typeof Char91Char93TasksRoute
  '/-/team': typeof Char91Char93TeamRoute
  '/-/today': typeof Char91Char93TodayRoute
  '/authentication/password-reset': typeof AuthenticationPasswordResetRoute
  '/-/': typeof Char91Char93IndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/-/account/security': typeof Char91Char93AccountSecurityRoute
  '/-/invitation/$invitationId': typeof Char91Char93InvitationInvitationIdRoute
  '/-/account/': typeof Char91Char93AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/-'
    | '/authentication'
    | '/support'
    | '/-/$aspect'
    | '/-/account'
    | '/-/agents'
    | '/-/explore'
    | '/-/profile'
    | '/-/tasks'
    | '/-/team'
    | '/-/today'
    | '/authentication/password-reset'
    | '/-/'
    | '/authentication/'
    | '/-/account/security'
    | '/-/invitation/$invitationId'
    | '/-/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/support'
    | '/-/$aspect'
    | '/-/agents'
    | '/-/explore'
    | '/-/profile'
    | '/-/tasks'
    | '/-/team'
    | '/-/today'
    | '/authentication/password-reset'
    | '/-'
    | '/authentication'
    | '/-/account/security'
    | '/-/invitation/$invitationId'
    | '/-/account'
  id:
    | '__root__'
    | '/'
    | '/-'
    | '/authentication'
    | '/support'
    | '/-/$aspect'
    | '/-/account'
    | '/-/agents'
    | '/-/explore'
    | '/-/profile'
    | '/-/tasks'
    | '/-/team'
    | '/-/today'
    | '/authentication/password-reset'
    | '/-/'
    | '/authentication/'
    | '/-/account/security'
    | '/-/invitation/$invitationId'
    | '/-/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91Char93Route: typeof Char91Char93RouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-': {
      id: '/-'
      path: '/-'
      fullPath: '/-'
      preLoaderRoute: typeof Char91Char93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/': {
      id: '/-/'
      path: '/'
      fullPath: '/-/'
      preLoaderRoute: typeof Char91Char93IndexRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/$aspect': {
      id: '/-/$aspect'
      path: '/$aspect'
      fullPath: '/-/$aspect'
      preLoaderRoute: typeof Char91Char93AspectRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/account': {
      id: '/-/account'
      path: '/account'
      fullPath: '/-/account'
      preLoaderRoute: typeof Char91Char93AccountRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/agents': {
      id: '/-/agents'
      path: '/agents'
      fullPath: '/-/agents'
      preLoaderRoute: typeof Char91Char93AgentsRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/explore': {
      id: '/-/explore'
      path: '/explore'
      fullPath: '/-/explore'
      preLoaderRoute: typeof Char91Char93ExploreRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/profile': {
      id: '/-/profile'
      path: '/profile'
      fullPath: '/-/profile'
      preLoaderRoute: typeof Char91Char93ProfileRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/tasks': {
      id: '/-/tasks'
      path: '/tasks'
      fullPath: '/-/tasks'
      preLoaderRoute: typeof Char91Char93TasksRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/team': {
      id: '/-/team'
      path: '/team'
      fullPath: '/-/team'
      preLoaderRoute: typeof Char91Char93TeamRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/-/today': {
      id: '/-/today'
      path: '/today'
      fullPath: '/-/today'
      preLoaderRoute: typeof Char91Char93TodayRouteImport
      parentRoute: typeof Char91Char93Route
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/authentication/password-reset': {
      id: '/authentication/password-reset'
      path: '/password-reset'
      fullPath: '/authentication/password-reset'
      preLoaderRoute: typeof AuthenticationPasswordResetRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/-/account/': {
      id: '/-/account/'
      path: '/'
      fullPath: '/-/account/'
      preLoaderRoute: typeof Char91Char93AccountIndexRouteImport
      parentRoute: typeof Char91Char93AccountRoute
    }
    '/-/account/security': {
      id: '/-/account/security'
      path: '/security'
      fullPath: '/-/account/security'
      preLoaderRoute: typeof Char91Char93AccountSecurityRouteImport
      parentRoute: typeof Char91Char93AccountRoute
    }
    '/-/invitation/$invitationId': {
      id: '/-/invitation/$invitationId'
      path: '/invitation/$invitationId'
      fullPath: '/-/invitation/$invitationId'
      preLoaderRoute: typeof Char91Char93InvitationInvitationIdRouteImport
      parentRoute: typeof Char91Char93Route
    }
  }
}

interface Char91Char93AccountRouteChildren {
  Char91Char93AccountSecurityRoute: typeof Char91Char93AccountSecurityRoute
  Char91Char93AccountIndexRoute: typeof Char91Char93AccountIndexRoute
}

const Char91Char93AccountRouteChildren: Char91Char93AccountRouteChildren = {
  Char91Char93AccountSecurityRoute: Char91Char93AccountSecurityRoute,
  Char91Char93AccountIndexRoute: Char91Char93AccountIndexRoute,
}

const Char91Char93AccountRouteWithChildren =
  Char91Char93AccountRoute._addFileChildren(Char91Char93AccountRouteChildren)

interface Char91Char93RouteChildren {
  Char91Char93AspectRoute: typeof Char91Char93AspectRoute
  Char91Char93AccountRoute: typeof Char91Char93AccountRouteWithChildren
  Char91Char93AgentsRoute: typeof Char91Char93AgentsRoute
  Char91Char93ExploreRoute: typeof Char91Char93ExploreRoute
  Char91Char93ProfileRoute: typeof Char91Char93ProfileRoute
  Char91Char93TasksRoute: typeof Char91Char93TasksRoute
  Char91Char93TeamRoute: typeof Char91Char93TeamRoute
  Char91Char93TodayRoute: typeof Char91Char93TodayRoute
  Char91Char93IndexRoute: typeof Char91Char93IndexRoute
  Char91Char93InvitationInvitationIdRoute: typeof Char91Char93InvitationInvitationIdRoute
}

const Char91Char93RouteChildren: Char91Char93RouteChildren = {
  Char91Char93AspectRoute: Char91Char93AspectRoute,
  Char91Char93AccountRoute: Char91Char93AccountRouteWithChildren,
  Char91Char93AgentsRoute: Char91Char93AgentsRoute,
  Char91Char93ExploreRoute: Char91Char93ExploreRoute,
  Char91Char93ProfileRoute: Char91Char93ProfileRoute,
  Char91Char93TasksRoute: Char91Char93TasksRoute,
  Char91Char93TeamRoute: Char91Char93TeamRoute,
  Char91Char93TodayRoute: Char91Char93TodayRoute,
  Char91Char93IndexRoute: Char91Char93IndexRoute,
  Char91Char93InvitationInvitationIdRoute:
    Char91Char93InvitationInvitationIdRoute,
}

const Char91Char93RouteWithChildren = Char91Char93Route._addFileChildren(
  Char91Char93RouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationPasswordResetRoute: typeof AuthenticationPasswordResetRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationPasswordResetRoute: AuthenticationPasswordResetRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91Char93Route: Char91Char93RouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
