/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrologueRouteImport } from './routes/prologue'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as AuthenticationPasswordResetRouteImport } from './routes/authentication/password-reset'
import { Route as AuthenticatedAppOrganizationSlugRouteImport } from './routes/_authenticated/_app/$organizationSlug'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/_app/account'
import { Route as AuthenticatedAppAdministrationRouteImport } from './routes/_authenticated/_app/administration'
import { Route as AuthenticatedAppTodayRouteImport } from './routes/_authenticated/_app/today'
import { Route as AuthenticatedInvitationInvitationIdRouteImport } from './routes/_authenticated/invitation.$invitationId'
import { Route as AuthenticatedAppOrganizationSlugIndexRouteImport } from './routes/_authenticated/_app/$organizationSlug/index'
import { Route as AuthenticatedAppOrganizationSlugBuildInPublicRouteImport } from './routes/_authenticated/_app/$organizationSlug/build-in-public'
import { Route as AuthenticatedAppOrganizationSlugConversationsRouteImport } from './routes/_authenticated/_app/$organizationSlug/conversations'
import { Route as AuthenticatedAppOrganizationSlugExploreRouteImport } from './routes/_authenticated/_app/$organizationSlug/explore'
import { Route as AuthenticatedAppOrganizationSlugProfileRouteImport } from './routes/_authenticated/_app/$organizationSlug/profile'
import { Route as AuthenticatedAppOrganizationSlugTeamRouteImport } from './routes/_authenticated/_app/$organizationSlug/team'
import { Route as AuthenticatedAppOrganizationSlugTodayRouteImport } from './routes/_authenticated/_app/$organizationSlug/today'
import { Route as AuthenticatedAppAccountIndexRouteImport } from './routes/_authenticated/_app/account/index'
import { Route as AuthenticatedAppAccountSecurityRouteImport } from './routes/_authenticated/_app/account/security'
import { Route as AuthenticatedAppAdministrationIndexRouteImport } from './routes/_authenticated/_app/administration/index'
import { Route as AuthenticatedAppAdministrationOrganizationsRouteImport } from './routes/_authenticated/_app/administration/organizations'
import { Route as AuthenticatedAppAdministrationUsersRouteImport } from './routes/_authenticated/_app/administration/users'
import { Route as AuthenticatedAppOrganizationSlugAspectsAspectRouteImport } from './routes/_authenticated/_app/$organizationSlug/aspects.$aspect'
import { Route as AuthenticatedAppOrganizationSlugConversationsIndexRouteImport } from './routes/_authenticated/_app/$organizationSlug/conversations.index'
import { Route as AuthenticatedAppOrganizationSlugConversationsConversationIdRouteImport } from './routes/_authenticated/_app/$organizationSlug/conversations.$conversationId'
import { Route as AuthenticatedAppOrganizationSlugKnowledgeIndexRouteImport } from './routes/_authenticated/_app/$organizationSlug/knowledge.index'
import { Route as AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRouteImport } from './routes/_authenticated/_app/$organizationSlug/knowledge.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrologueRoute = PrologueRouteImport.update({
  id: '/prologue',
  path: '/prologue',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationPasswordResetRoute =
  AuthenticationPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => AuthenticationRoute,
  } as any)
const AuthenticatedAppOrganizationSlugRoute =
  AuthenticatedAppOrganizationSlugRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdministrationRoute =
  AuthenticatedAppAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTodayRoute = AuthenticatedAppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedInvitationInvitationIdRoute =
  AuthenticatedInvitationInvitationIdRouteImport.update({
    id: '/invitation/$invitationId',
    path: '/invitation/$invitationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppOrganizationSlugIndexRoute =
  AuthenticatedAppOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugBuildInPublicRoute =
  AuthenticatedAppOrganizationSlugBuildInPublicRouteImport.update({
    id: '/build-in-public',
    path: '/build-in-public',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugConversationsRoute =
  AuthenticatedAppOrganizationSlugConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugExploreRoute =
  AuthenticatedAppOrganizationSlugExploreRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugProfileRoute =
  AuthenticatedAppOrganizationSlugProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugTeamRoute =
  AuthenticatedAppOrganizationSlugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugTodayRoute =
  AuthenticatedAppOrganizationSlugTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppAccountIndexRoute =
  AuthenticatedAppAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAccountRoute,
  } as any)
const AuthenticatedAppAccountSecurityRoute =
  AuthenticatedAppAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAppAccountRoute,
  } as any)
const AuthenticatedAppAdministrationIndexRoute =
  AuthenticatedAppAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdministrationRoute,
  } as any)
const AuthenticatedAppAdministrationOrganizationsRoute =
  AuthenticatedAppAdministrationOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAppAdministrationRoute,
  } as any)
const AuthenticatedAppAdministrationUsersRoute =
  AuthenticatedAppAdministrationUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAppAdministrationRoute,
  } as any)
const AuthenticatedAppOrganizationSlugAspectsAspectRoute =
  AuthenticatedAppOrganizationSlugAspectsAspectRouteImport.update({
    id: '/aspects/$aspect',
    path: '/aspects/$aspect',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugConversationsIndexRoute =
  AuthenticatedAppOrganizationSlugConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppOrganizationSlugConversationsRoute,
  } as any)
const AuthenticatedAppOrganizationSlugConversationsConversationIdRoute =
  AuthenticatedAppOrganizationSlugConversationsConversationIdRouteImport.update(
    {
      id: '/$conversationId',
      path: '/$conversationId',
      getParentRoute: () => AuthenticatedAppOrganizationSlugConversationsRoute,
    } as any,
  )
const AuthenticatedAppOrganizationSlugKnowledgeIndexRoute =
  AuthenticatedAppOrganizationSlugKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)
const AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute =
  AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRouteImport.update({
    id: '/knowledge/$documentId',
    path: '/knowledge/$documentId',
    getParentRoute: () => AuthenticatedAppOrganizationSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication': typeof AuthenticationRouteWithChildren
  '/legal': typeof LegalRoute
  '/prologue': typeof PrologueRoute
  '/support': typeof SupportRoute
  '/authentication/password-reset': typeof AuthenticationPasswordResetRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/$organizationSlug': typeof AuthenticatedAppOrganizationSlugRouteWithChildren
  '/account': typeof AuthenticatedAppAccountRouteWithChildren
  '/administration': typeof AuthenticatedAppAdministrationRouteWithChildren
  '/today': typeof AuthenticatedAppTodayRoute
  '/invitation/$invitationId': typeof AuthenticatedInvitationInvitationIdRoute
  '/$organizationSlug/build-in-public': typeof AuthenticatedAppOrganizationSlugBuildInPublicRoute
  '/$organizationSlug/conversations': typeof AuthenticatedAppOrganizationSlugConversationsRouteWithChildren
  '/$organizationSlug/explore': typeof AuthenticatedAppOrganizationSlugExploreRoute
  '/$organizationSlug/profile': typeof AuthenticatedAppOrganizationSlugProfileRoute
  '/$organizationSlug/team': typeof AuthenticatedAppOrganizationSlugTeamRoute
  '/$organizationSlug/today': typeof AuthenticatedAppOrganizationSlugTodayRoute
  '/account/security': typeof AuthenticatedAppAccountSecurityRoute
  '/administration/organizations': typeof AuthenticatedAppAdministrationOrganizationsRoute
  '/administration/users': typeof AuthenticatedAppAdministrationUsersRoute
  '/$organizationSlug/': typeof AuthenticatedAppOrganizationSlugIndexRoute
  '/account/': typeof AuthenticatedAppAccountIndexRoute
  '/administration/': typeof AuthenticatedAppAdministrationIndexRoute
  '/$organizationSlug/aspects/$aspect': typeof AuthenticatedAppOrganizationSlugAspectsAspectRoute
  '/$organizationSlug/conversations/$conversationId': typeof AuthenticatedAppOrganizationSlugConversationsConversationIdRoute
  '/$organizationSlug/knowledge/$documentId': typeof AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute
  '/$organizationSlug/conversations/': typeof AuthenticatedAppOrganizationSlugConversationsIndexRoute
  '/$organizationSlug/knowledge/': typeof AuthenticatedAppOrganizationSlugKnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/prologue': typeof PrologueRoute
  '/support': typeof SupportRoute
  '/authentication/password-reset': typeof AuthenticationPasswordResetRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/today': typeof AuthenticatedAppTodayRoute
  '/invitation/$invitationId': typeof AuthenticatedInvitationInvitationIdRoute
  '/$organizationSlug/build-in-public': typeof AuthenticatedAppOrganizationSlugBuildInPublicRoute
  '/$organizationSlug/explore': typeof AuthenticatedAppOrganizationSlugExploreRoute
  '/$organizationSlug/profile': typeof AuthenticatedAppOrganizationSlugProfileRoute
  '/$organizationSlug/team': typeof AuthenticatedAppOrganizationSlugTeamRoute
  '/$organizationSlug/today': typeof AuthenticatedAppOrganizationSlugTodayRoute
  '/account/security': typeof AuthenticatedAppAccountSecurityRoute
  '/administration/organizations': typeof AuthenticatedAppAdministrationOrganizationsRoute
  '/administration/users': typeof AuthenticatedAppAdministrationUsersRoute
  '/$organizationSlug': typeof AuthenticatedAppOrganizationSlugIndexRoute
  '/account': typeof AuthenticatedAppAccountIndexRoute
  '/administration': typeof AuthenticatedAppAdministrationIndexRoute
  '/$organizationSlug/aspects/$aspect': typeof AuthenticatedAppOrganizationSlugAspectsAspectRoute
  '/$organizationSlug/conversations/$conversationId': typeof AuthenticatedAppOrganizationSlugConversationsConversationIdRoute
  '/$organizationSlug/knowledge/$documentId': typeof AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute
  '/$organizationSlug/conversations': typeof AuthenticatedAppOrganizationSlugConversationsIndexRoute
  '/$organizationSlug/knowledge': typeof AuthenticatedAppOrganizationSlugKnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/authentication': typeof AuthenticationRouteWithChildren
  '/legal': typeof LegalRoute
  '/prologue': typeof PrologueRoute
  '/support': typeof SupportRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/authentication/password-reset': typeof AuthenticationPasswordResetRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/_authenticated/_app/$organizationSlug': typeof AuthenticatedAppOrganizationSlugRouteWithChildren
  '/_authenticated/_app/account': typeof AuthenticatedAppAccountRouteWithChildren
  '/_authenticated/_app/administration': typeof AuthenticatedAppAdministrationRouteWithChildren
  '/_authenticated/_app/today': typeof AuthenticatedAppTodayRoute
  '/_authenticated/invitation/$invitationId': typeof AuthenticatedInvitationInvitationIdRoute
  '/_authenticated/_app/$organizationSlug/build-in-public': typeof AuthenticatedAppOrganizationSlugBuildInPublicRoute
  '/_authenticated/_app/$organizationSlug/conversations': typeof AuthenticatedAppOrganizationSlugConversationsRouteWithChildren
  '/_authenticated/_app/$organizationSlug/explore': typeof AuthenticatedAppOrganizationSlugExploreRoute
  '/_authenticated/_app/$organizationSlug/profile': typeof AuthenticatedAppOrganizationSlugProfileRoute
  '/_authenticated/_app/$organizationSlug/team': typeof AuthenticatedAppOrganizationSlugTeamRoute
  '/_authenticated/_app/$organizationSlug/today': typeof AuthenticatedAppOrganizationSlugTodayRoute
  '/_authenticated/_app/account/security': typeof AuthenticatedAppAccountSecurityRoute
  '/_authenticated/_app/administration/organizations': typeof AuthenticatedAppAdministrationOrganizationsRoute
  '/_authenticated/_app/administration/users': typeof AuthenticatedAppAdministrationUsersRoute
  '/_authenticated/_app/$organizationSlug/': typeof AuthenticatedAppOrganizationSlugIndexRoute
  '/_authenticated/_app/account/': typeof AuthenticatedAppAccountIndexRoute
  '/_authenticated/_app/administration/': typeof AuthenticatedAppAdministrationIndexRoute
  '/_authenticated/_app/$organizationSlug/aspects/$aspect': typeof AuthenticatedAppOrganizationSlugAspectsAspectRoute
  '/_authenticated/_app/$organizationSlug/conversations/$conversationId': typeof AuthenticatedAppOrganizationSlugConversationsConversationIdRoute
  '/_authenticated/_app/$organizationSlug/knowledge/$documentId': typeof AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute
  '/_authenticated/_app/$organizationSlug/conversations/': typeof AuthenticatedAppOrganizationSlugConversationsIndexRoute
  '/_authenticated/_app/$organizationSlug/knowledge/': typeof AuthenticatedAppOrganizationSlugKnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication'
    | '/legal'
    | '/prologue'
    | '/support'
    | '/authentication/password-reset'
    | '/authentication/'
    | '/$organizationSlug'
    | '/account'
    | '/administration'
    | '/today'
    | '/invitation/$invitationId'
    | '/$organizationSlug/build-in-public'
    | '/$organizationSlug/conversations'
    | '/$organizationSlug/explore'
    | '/$organizationSlug/profile'
    | '/$organizationSlug/team'
    | '/$organizationSlug/today'
    | '/account/security'
    | '/administration/organizations'
    | '/administration/users'
    | '/$organizationSlug/'
    | '/account/'
    | '/administration/'
    | '/$organizationSlug/aspects/$aspect'
    | '/$organizationSlug/conversations/$conversationId'
    | '/$organizationSlug/knowledge/$documentId'
    | '/$organizationSlug/conversations/'
    | '/$organizationSlug/knowledge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/prologue'
    | '/support'
    | '/authentication/password-reset'
    | '/authentication'
    | '/today'
    | '/invitation/$invitationId'
    | '/$organizationSlug/build-in-public'
    | '/$organizationSlug/explore'
    | '/$organizationSlug/profile'
    | '/$organizationSlug/team'
    | '/$organizationSlug/today'
    | '/account/security'
    | '/administration/organizations'
    | '/administration/users'
    | '/$organizationSlug'
    | '/account'
    | '/administration'
    | '/$organizationSlug/aspects/$aspect'
    | '/$organizationSlug/conversations/$conversationId'
    | '/$organizationSlug/knowledge/$documentId'
    | '/$organizationSlug/conversations'
    | '/$organizationSlug/knowledge'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/authentication'
    | '/legal'
    | '/prologue'
    | '/support'
    | '/_authenticated/_app'
    | '/authentication/password-reset'
    | '/authentication/'
    | '/_authenticated/_app/$organizationSlug'
    | '/_authenticated/_app/account'
    | '/_authenticated/_app/administration'
    | '/_authenticated/_app/today'
    | '/_authenticated/invitation/$invitationId'
    | '/_authenticated/_app/$organizationSlug/build-in-public'
    | '/_authenticated/_app/$organizationSlug/conversations'
    | '/_authenticated/_app/$organizationSlug/explore'
    | '/_authenticated/_app/$organizationSlug/profile'
    | '/_authenticated/_app/$organizationSlug/team'
    | '/_authenticated/_app/$organizationSlug/today'
    | '/_authenticated/_app/account/security'
    | '/_authenticated/_app/administration/organizations'
    | '/_authenticated/_app/administration/users'
    | '/_authenticated/_app/$organizationSlug/'
    | '/_authenticated/_app/account/'
    | '/_authenticated/_app/administration/'
    | '/_authenticated/_app/$organizationSlug/aspects/$aspect'
    | '/_authenticated/_app/$organizationSlug/conversations/$conversationId'
    | '/_authenticated/_app/$organizationSlug/knowledge/$documentId'
    | '/_authenticated/_app/$organizationSlug/conversations/'
    | '/_authenticated/_app/$organizationSlug/knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
  LegalRoute: typeof LegalRoute
  PrologueRoute: typeof PrologueRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prologue': {
      id: '/prologue'
      path: '/prologue'
      fullPath: '/prologue'
      preLoaderRoute: typeof PrologueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/authentication/password-reset': {
      id: '/authentication/password-reset'
      path: '/password-reset'
      fullPath: '/authentication/password-reset'
      preLoaderRoute: typeof AuthenticationPasswordResetRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authenticated/_app/$organizationSlug': {
      id: '/_authenticated/_app/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/account': {
      id: '/_authenticated/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/administration': {
      id: '/_authenticated/_app/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAppAdministrationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/today': {
      id: '/_authenticated/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedAppTodayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/invitation/$invitationId': {
      id: '/_authenticated/invitation/$invitationId'
      path: '/invitation/$invitationId'
      fullPath: '/invitation/$invitationId'
      preLoaderRoute: typeof AuthenticatedInvitationInvitationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/$organizationSlug/': {
      id: '/_authenticated/_app/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugIndexRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/build-in-public': {
      id: '/_authenticated/_app/$organizationSlug/build-in-public'
      path: '/build-in-public'
      fullPath: '/$organizationSlug/build-in-public'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugBuildInPublicRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/conversations': {
      id: '/_authenticated/_app/$organizationSlug/conversations'
      path: '/conversations'
      fullPath: '/$organizationSlug/conversations'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugConversationsRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/explore': {
      id: '/_authenticated/_app/$organizationSlug/explore'
      path: '/explore'
      fullPath: '/$organizationSlug/explore'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugExploreRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/profile': {
      id: '/_authenticated/_app/$organizationSlug/profile'
      path: '/profile'
      fullPath: '/$organizationSlug/profile'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugProfileRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/team': {
      id: '/_authenticated/_app/$organizationSlug/team'
      path: '/team'
      fullPath: '/$organizationSlug/team'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugTeamRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/today': {
      id: '/_authenticated/_app/$organizationSlug/today'
      path: '/today'
      fullPath: '/$organizationSlug/today'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugTodayRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/account/': {
      id: '/_authenticated/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAppAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAppAccountRoute
    }
    '/_authenticated/_app/account/security': {
      id: '/_authenticated/_app/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAppAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedAppAccountRoute
    }
    '/_authenticated/_app/administration/': {
      id: '/_authenticated/_app/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof AuthenticatedAppAdministrationIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdministrationRoute
    }
    '/_authenticated/_app/administration/organizations': {
      id: '/_authenticated/_app/administration/organizations'
      path: '/organizations'
      fullPath: '/administration/organizations'
      preLoaderRoute: typeof AuthenticatedAppAdministrationOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAppAdministrationRoute
    }
    '/_authenticated/_app/administration/users': {
      id: '/_authenticated/_app/administration/users'
      path: '/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof AuthenticatedAppAdministrationUsersRouteImport
      parentRoute: typeof AuthenticatedAppAdministrationRoute
    }
    '/_authenticated/_app/$organizationSlug/aspects/$aspect': {
      id: '/_authenticated/_app/$organizationSlug/aspects/$aspect'
      path: '/aspects/$aspect'
      fullPath: '/$organizationSlug/aspects/$aspect'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugAspectsAspectRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/conversations/': {
      id: '/_authenticated/_app/$organizationSlug/conversations/'
      path: '/'
      fullPath: '/$organizationSlug/conversations/'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugConversationsRoute
    }
    '/_authenticated/_app/$organizationSlug/conversations/$conversationId': {
      id: '/_authenticated/_app/$organizationSlug/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/$organizationSlug/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugConversationsRoute
    }
    '/_authenticated/_app/$organizationSlug/knowledge/': {
      id: '/_authenticated/_app/$organizationSlug/knowledge/'
      path: '/knowledge'
      fullPath: '/$organizationSlug/knowledge/'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
    '/_authenticated/_app/$organizationSlug/knowledge/$documentId': {
      id: '/_authenticated/_app/$organizationSlug/knowledge/$documentId'
      path: '/knowledge/$documentId'
      fullPath: '/$organizationSlug/knowledge/$documentId'
      preLoaderRoute: typeof AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationSlugRoute
    }
  }
}

interface AuthenticatedAppOrganizationSlugConversationsRouteChildren {
  AuthenticatedAppOrganizationSlugConversationsConversationIdRoute: typeof AuthenticatedAppOrganizationSlugConversationsConversationIdRoute
  AuthenticatedAppOrganizationSlugConversationsIndexRoute: typeof AuthenticatedAppOrganizationSlugConversationsIndexRoute
}

const AuthenticatedAppOrganizationSlugConversationsRouteChildren: AuthenticatedAppOrganizationSlugConversationsRouteChildren =
  {
    AuthenticatedAppOrganizationSlugConversationsConversationIdRoute:
      AuthenticatedAppOrganizationSlugConversationsConversationIdRoute,
    AuthenticatedAppOrganizationSlugConversationsIndexRoute:
      AuthenticatedAppOrganizationSlugConversationsIndexRoute,
  }

const AuthenticatedAppOrganizationSlugConversationsRouteWithChildren =
  AuthenticatedAppOrganizationSlugConversationsRoute._addFileChildren(
    AuthenticatedAppOrganizationSlugConversationsRouteChildren,
  )

interface AuthenticatedAppOrganizationSlugRouteChildren {
  AuthenticatedAppOrganizationSlugBuildInPublicRoute: typeof AuthenticatedAppOrganizationSlugBuildInPublicRoute
  AuthenticatedAppOrganizationSlugConversationsRoute: typeof AuthenticatedAppOrganizationSlugConversationsRouteWithChildren
  AuthenticatedAppOrganizationSlugExploreRoute: typeof AuthenticatedAppOrganizationSlugExploreRoute
  AuthenticatedAppOrganizationSlugProfileRoute: typeof AuthenticatedAppOrganizationSlugProfileRoute
  AuthenticatedAppOrganizationSlugTeamRoute: typeof AuthenticatedAppOrganizationSlugTeamRoute
  AuthenticatedAppOrganizationSlugTodayRoute: typeof AuthenticatedAppOrganizationSlugTodayRoute
  AuthenticatedAppOrganizationSlugIndexRoute: typeof AuthenticatedAppOrganizationSlugIndexRoute
  AuthenticatedAppOrganizationSlugAspectsAspectRoute: typeof AuthenticatedAppOrganizationSlugAspectsAspectRoute
  AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute: typeof AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute
  AuthenticatedAppOrganizationSlugKnowledgeIndexRoute: typeof AuthenticatedAppOrganizationSlugKnowledgeIndexRoute
}

const AuthenticatedAppOrganizationSlugRouteChildren: AuthenticatedAppOrganizationSlugRouteChildren =
  {
    AuthenticatedAppOrganizationSlugBuildInPublicRoute:
      AuthenticatedAppOrganizationSlugBuildInPublicRoute,
    AuthenticatedAppOrganizationSlugConversationsRoute:
      AuthenticatedAppOrganizationSlugConversationsRouteWithChildren,
    AuthenticatedAppOrganizationSlugExploreRoute:
      AuthenticatedAppOrganizationSlugExploreRoute,
    AuthenticatedAppOrganizationSlugProfileRoute:
      AuthenticatedAppOrganizationSlugProfileRoute,
    AuthenticatedAppOrganizationSlugTeamRoute:
      AuthenticatedAppOrganizationSlugTeamRoute,
    AuthenticatedAppOrganizationSlugTodayRoute:
      AuthenticatedAppOrganizationSlugTodayRoute,
    AuthenticatedAppOrganizationSlugIndexRoute:
      AuthenticatedAppOrganizationSlugIndexRoute,
    AuthenticatedAppOrganizationSlugAspectsAspectRoute:
      AuthenticatedAppOrganizationSlugAspectsAspectRoute,
    AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute:
      AuthenticatedAppOrganizationSlugKnowledgeDocumentIdRoute,
    AuthenticatedAppOrganizationSlugKnowledgeIndexRoute:
      AuthenticatedAppOrganizationSlugKnowledgeIndexRoute,
  }

const AuthenticatedAppOrganizationSlugRouteWithChildren =
  AuthenticatedAppOrganizationSlugRoute._addFileChildren(
    AuthenticatedAppOrganizationSlugRouteChildren,
  )

interface AuthenticatedAppAccountRouteChildren {
  AuthenticatedAppAccountSecurityRoute: typeof AuthenticatedAppAccountSecurityRoute
  AuthenticatedAppAccountIndexRoute: typeof AuthenticatedAppAccountIndexRoute
}

const AuthenticatedAppAccountRouteChildren: AuthenticatedAppAccountRouteChildren =
  {
    AuthenticatedAppAccountSecurityRoute: AuthenticatedAppAccountSecurityRoute,
    AuthenticatedAppAccountIndexRoute: AuthenticatedAppAccountIndexRoute,
  }

const AuthenticatedAppAccountRouteWithChildren =
  AuthenticatedAppAccountRoute._addFileChildren(
    AuthenticatedAppAccountRouteChildren,
  )

interface AuthenticatedAppAdministrationRouteChildren {
  AuthenticatedAppAdministrationOrganizationsRoute: typeof AuthenticatedAppAdministrationOrganizationsRoute
  AuthenticatedAppAdministrationUsersRoute: typeof AuthenticatedAppAdministrationUsersRoute
  AuthenticatedAppAdministrationIndexRoute: typeof AuthenticatedAppAdministrationIndexRoute
}

const AuthenticatedAppAdministrationRouteChildren: AuthenticatedAppAdministrationRouteChildren =
  {
    AuthenticatedAppAdministrationOrganizationsRoute:
      AuthenticatedAppAdministrationOrganizationsRoute,
    AuthenticatedAppAdministrationUsersRoute:
      AuthenticatedAppAdministrationUsersRoute,
    AuthenticatedAppAdministrationIndexRoute:
      AuthenticatedAppAdministrationIndexRoute,
  }

const AuthenticatedAppAdministrationRouteWithChildren =
  AuthenticatedAppAdministrationRoute._addFileChildren(
    AuthenticatedAppAdministrationRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppOrganizationSlugRoute: typeof AuthenticatedAppOrganizationSlugRouteWithChildren
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRouteWithChildren
  AuthenticatedAppAdministrationRoute: typeof AuthenticatedAppAdministrationRouteWithChildren
  AuthenticatedAppTodayRoute: typeof AuthenticatedAppTodayRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppOrganizationSlugRoute:
    AuthenticatedAppOrganizationSlugRouteWithChildren,
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRouteWithChildren,
  AuthenticatedAppAdministrationRoute:
    AuthenticatedAppAdministrationRouteWithChildren,
  AuthenticatedAppTodayRoute: AuthenticatedAppTodayRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedInvitationInvitationIdRoute: typeof AuthenticatedInvitationInvitationIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedInvitationInvitationIdRoute:
    AuthenticatedInvitationInvitationIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationPasswordResetRoute: typeof AuthenticationPasswordResetRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationPasswordResetRoute: AuthenticationPasswordResetRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
  LegalRoute: LegalRoute,
  PrologueRoute: PrologueRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
